# Generated by Django 5.2 on 2025-04-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('pname', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=50)),
                ('id_im', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
                ('base64', models.CharField(max_length=50)),
            ],
        ),
    ]
